const { PERMISSIONS } = require("./permission");

exports.ROLES = {
  ADMIN: [
    PERMISSIONS.ASSET_CREATE,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSET_UPDATE,
    PERMISSIONS.ASSET_DELETE,
    PERMISSIONS.USER_MANAGE,
  ],

  ASSET_MANAGER: [
    PERMISSIONS.ASSET_CREATE,
    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSET_UPDATE,
  ],

  USER: [
    PERMISSIONS.ASSET_VIEW,
  ],
};
